license="All Rights Reserved"
issueTrackerURL="https://github.com/UpperMoon0/FTB-IC-Expansion/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/UpperMoon0/FTB-IC-Expansion"
authors="NsTut"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ftbic"
type="required"
versionRange="[${ftbic_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ftbicec"
type="required"
versionRange="[${core_version},)"
ordering="AFTER"
side="BOTH"
